export const weatherImagesNight = {
    1000: require('../assets/images/clear-night.png'),
    1003: require('../assets/images/cloudy-night.png'),
    1189: require('../assets/images/moderate-rain-night.png'),
    1063: require('../assets/images/moderate-rain-night.png'),
    1009: require('../assets/images/cloudy.png'),
    1006: require('../assets/images/cloudy.png'),
    1180: require('../assets/images/moderate-rain-night.png'),
    1183: require('../assets/images/moderate-rain-night.png'),
    1186: require('../assets/images/moderate-rain-night.png'),
    1213: require('../assets/images/light-snow.png'),
    1195: require('../assets/images/rain.png'),
    1192: require('../assets/images/rain.png'),
    1201: require('../assets/images/rain.png'),
    1243: require('../assets/images/rain.png'),
    1276: require('../assets/images/electric-storm.png'),
    1030: require('../assets/images/mist.png'),
    1135: require('../assets/images/mist.png'),
    1147: require('../assets/images/mist.png'),
    1153: require('../assets/images/rain.png'),
    1087: require('../assets/images/electric-storm.png'),
    1150: require('../assets/images/rain.png'),
    1204: require('../assets/images/sleet.png'),
    1207: require('../assets/images/sleet.png'),
    'other': require('../assets/images/moderate-rain-night.png')
}